# Generated by Django 6.0.2 on 2026-02-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_created'], 'verbose_name': 'مقال', 'verbose_name_plural': 'المقالات'},
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('published', 'منشور')], default='draft', max_length=10),
        ),
    ]
